import type { Metadata } from "next";
import { Faustina, M_PLUS_1 } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const faustina = Faustina({
  subsets: ["latin"],
});

const mPlus1 = M_PLUS_1({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Simple SNS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mPlus1.className} antialiased overflow-y-scroll`}>
        <div className="grid grid-rows-[60px_1fr] justify-items-center min-h-screen gap-8">
          <nav className="bg-white w-full shadow-md sticky top-0">
            <h1 className={`text-center text-4xl ${faustina.className}`}>
              <Link href="/" className="no-underline">
                The Simple SNS
              </Link>
            </h1>
          </nav>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
